spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_PATH:/swagger-ui.html}

server:
  port: 8083

token:
  signing:
    key: 289C9EDB672E70546B0DCD26077540A6C384E6544AF8118573B7EC9D25E42B1A
