version: '3.8'

services:
  book-author-service:
    build:
      context: ./book-author-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8088
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: books
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - monitoring

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d books" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  monitoring:
    driver: bridge