server:
  port: ${SERVER_PORT:8089}
spring:
  application:
    name: users-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_DATABASE:users}"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  cache:
    type: ${SPRING_CACHE_TYPE:none}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    clean-disabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info

  health:
    redis:
      enabled: ${MANAGEMENT_HEALTH_REDIS_ENABLED:false}

  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework: INFO
    org.springframework.cache: TRACE
    org.springframework.web: INFO
    ROOT: INFO
    org.zalando.logbook: TRACE

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_PATH:/swagger-ui.html}

