global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'book-author-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['book-author-service:8088']
        labels:
          service: 'book-author-service'
    scrape_interval: 10s

  - job_name: 'users-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['users-service:8089']
        labels:
          service: 'users-service'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']