server:
  port: ${NOTIFICATION_SERVER_PORT:8085}
spring:
  application:
    name: email-notification

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: "false"
        auto.create.topics.enable: true
        spring.json.value.default.type: "moderation.notification.emailnotificationservice.model.contract.UserStatusChangedEvent"
    listener:
      ack-mode: RECORD

  mail:
    host: smtp.mail.ru
    port: 587
    username: andrey_kareev@inbox.ru
    password:  anJ3RLZ0HBnlaZhnwa40
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  kafka:
    topics:
      user-status-changed: user-status-changed-topic

logging:
  level:
    org.springframework: INFO
    org.springframework.cache: INFO
    org.springframework.web: INFO
    ROOT: INFO
    org.zalando.logbook: INFO

