apiVersion: apps/v1
kind: Deployment  # тип объекта
metadata:
  name: book-author-service
  namespace: bookstore
  labels:  # теги
    app: book-author-service
spec: # спецификация
  replicas: 3  # 3 реплики
  strategy: # как обновлять поды
    type: RollingUpdate # обновлять постепенно, но не все сразу
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # ноль задержки
  selector: # как найти поды, которыми управляет этот deployment (связка между deployment и подами)
    matchLabels:
      app: book-author-service
  template: # как должен выглядеть каждый под
    metadata:
      labels:
        app: book-author-service
    spec:
      affinity:
        podAntiAffinity: # правило размещения подов (не размещать несколького подов на одной ноде, нужно для high availability)
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - book-author-service
                topologyKey: kubernetes.io/hostname # по какому принциипу разделяем ноды
      containers: # контейнеры внутри пода
        - name: book-author-service
          image: book-author-service:latest
          imagePullPolicy: Never # берем локально, не лезем в интернет
          ports:
            - containerPort: 8088
              name: http
          env: # переменные окружения
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

          resources: # сколько CPU и памяти надо контейнеру
            requests: # столько гарантируем для scheduler
              memory: "512Mi"
              cpu: "250m"
            limits: # максимум для одного контейнера
              memory: "1Gi"
              cpu: "1000m"

          livenessProbe: # проверка на то, жив ли контейнер
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 40 # проверяем через 40 сек после запуска, т.к spring стартует секунд 20-30
            periodSeconds: 10 # как часто проверяем
            timeoutSeconds: 5
            failureThreshold: 3 # грохаем контейнер после трех неудачных попыток

          readinessProbe: # готов ли контейнер считывать трафик (готов ли обрабатывать запросы)
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
--- # разделитель между объектами в одном файле
apiVersion: v1
kind: Service # т.к. deployment создает поды ,которые недоступны снаружи, то Service открывает к ним доступ
metadata:
  name: book-author-service
  namespace: bookstore
spec:
  selector: # поиск всех подов по ключевому имени
    app: book-author-service
  ports:
    - port: 8088 # порт снаружи
      targetPort: 8088
      protocol: TCP
      name: http
  type: ClusterIP # виден только внутри кластера
  # Есть еще:
  # NodePort = видимый на всех нодах на одном порте (например :30000)
  # LoadBalancer = видимый внешне через облачный LB (AWS ELB, Azure LB)
  # ExternalName = алиас на DNS имя снаружи