apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: bookstore
  labels:
    app: users-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - users-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: users-service
          image: users-service:latest
          imagePullPolicy: Never # берем локально, не лезем в интернет
          ports:
            - containerPort: 8089
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: bookstore
spec:
  selector:
    app: users-service
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
  type: ClusterIP # только внутри кластера